<a href="https://colab.research.google.com/github/Shanidhanasrin/DATASCIENCE/blob/main/ds_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(marks)

[78 92 65 88 45 90 72 55]


In [ ]:
#total
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(np.sum(marks))

585


In [ ]:
#average
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(np.average(marks))

73.125


In [ ]:
#highest mark
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(np.max(marks))

92


In [ ]:
#lowest
import numpy as np
marks=np.array([78,92,65,88,45,90,72,55])
print(np.min(marks))

45


In [ ]:
#find student who score above 75
marks=np.array([78,92,65,88,45,90,72,55])
print(marks[marks>75])

[78 92 88 90]


In [ ]:
#below 50 and =50
marks=np.array([78,92,65,88,45,90,72,55])
print(marks[marks<=50])

[45]


In [ ]:
#sorting (ascenting order)
marks=np.array([78,92,65,88,45,90,72,55])
print(np.sort(marks))

[45 55 65 72 78 88 90 92]


In [ ]:
#range
marks=np.arange(1,21)
print(marks)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr1=np.zeros(5)
arr2=np.ones(4)
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
x=np.random.rand(10)
print(x)


[0.36259076 0.38339532 0.02112185 0.3899121  0.66945647 0.91785189
 0.33849965 0.82267406 0.58355657 0.71566292]


In [ ]:
s=np.random.randint(1,100,10)
print(s)
print(np.shape(s))


[20 19 87 77 96 94 58 28 53  4]
(10,)


In [ ]:
#find mean temperature
temperature=np.array([32,35,40,28,42,33])
print(np.mean(temperature))



35.0


In [ ]:
#find maximum and minimum
print(np.min(temperature))
print(np.max(temperature))

28
42


In [ ]:
#replace temperature above 38 with 38
temperature[temperature>38]=38                    #
print(temperature)

[32 35 38 28 38 33]


In [ ]:
#reshape the array into 2x3 matrix
print(temperature.reshape(2,3))

[[32 35 38]
 [28 38 33]]


In [ ]:
#display the first row and second column values
temp=temperature.reshape(2,3)
print(temp)
print(temp[0])
print(temp[:,2])

[[32 35 38]
 [28 38 33]]
[32 35 38]
[38 33]


In [ ]:
#slicing
c=[10,20,30,40,50,60,70,80]
print(c[0::7])
#print index 2 to 6
print(c[1:5])
#alternative element
print(c[::2])

[10, 80]
[20, 30, 40, 50]
[10, 30, 50, 70]


In [ ]:
#even index
a=np.array([1,2,3,4,5,6,7,8])
print(a)
print(np.where(a%2==0))
#odd index
print(np.where(a%2!=0))
#normal
print(a[a%2==0])
print(a[a%2!=0])


[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)
[2 4 6 8]
[1 3 5 7]
